### ISSUE TITLE
A view into the world of Mobile Apps

### ISSUE THREAD

**Issue by tshradheya** [nus-cs3281/2018#11]
# Topic
A view into the world of Mobile Applications

# PUMA

## Punch
Mark Zuckerberg confessing Facebook's biggest mistake and how they decided to drastically transform their mobile apps

## WIIFY

To have a better understanding of different types of mobile apps and their pros and cons so that you can make the right decision when building your own application

## Key Points

- It is important to build the right type of mobile app to avoid mistake which FB made
- There are different kinds of mobile apps and various technologies are used to build them
- Depending on the pros and cons of each type mobile app, one can have a better understanding of different kinds of mobile apps and their differences in terms of UI/UX, Performance, development process etc.
- FB constantly kept evolving with different kinds of mobile application

## Call to Action/Impact

Audience can now make a better decision on what app to build by knowing the requirements of the application

# Slides
[LT1.pptx](https://github.com/nus-cs3281/2018/files/1695502/LT1.pptx)

**Comment by damithc** [comment]
The talk was good but seems mostly instructional (like a lecture). For higher impact, choose a topic that calls for an action. For example, if the call to action is 'build the _right_ type of mobile app', the key points that are aligned with it can be,
* Choosing the right type is imprtant because ...
* Consider x when choosing the type
* Consider y when choosing the type

The roadmap can be (slightly different from keypoints):
* What are the types of mobile apps (this is not a key point, rather, it is some background info)
* Why it is an important choice
* Two factors you need to consider when choosing
