### ISSUE TITLE
Testing Android Apps

### ISSUE THREAD

**Issue by leeyh20** [nus-cs3281/2018#18]
**PUNCH:**
An app on android app store having many bad reviews about technical issues - Kim Kardashian's Kimoji app. 

**WIIFY:**
Properly testing android apps during development will make your development smoother, reduce end-user frustration and you will be happy too!

**Key Points:**
Why it is especially important to test android apps
Easily test android apps with Android Studio Tools:  Android Debug Bridge and Emulator
Easily test android apps automatically with automated test frameworks: Unit tests with Robolectric, integration tests, large-sized tests with Espresso

**Call to action:**
Test your android apps throughout your development phrase!

PPT file:
[Testing Android Apps](https://drive.google.com/file/d/1-E_6fPqdttK5B5Z_UMlx5Lz1QhYg4Q6x/view?usp=sharing)

**Comment by damithc** [comment]
>Why it is especially important to test android apps

This is a topic, not a point. It be something like 'Testing Android apps is especially important because ...'

My comment [here](https://github.com/nus-cs3281/2018/issues/11#issuecomment-363736265) applies to this talk as well. While it is a good talk, it can have more powerfull if the intended impact is actionable in addition to being instructional. e.g., 'Do more testing of your Android Apps'. i.e., call for 'do' in addition to 'know' and 'believe'
